import * as XLSX from "xlsx";
import { ParsedInvoiceData } from "./gemini";

// Export invoice data to Excel format
export function exportToExcel(
  data: ParsedInvoiceData,
  filename: string = "invoice_data"
): void {
  // Create worksheet data
  const worksheetData = [
    ["VectraLogic - Invoice Data Export"],
    [],
    ["Field", "Value"],
    ["Vendor Name", data.vendor || "N/A"],
    ["Invoice Date", data.date || "N/A"],
    ["Total Amount", data.amount || "N/A"],
    ["Currency", data.currency || "N/A"],
    [],
    ["Export Date", new Date().toISOString().split("T")[0]],
    ["Generated by", "VectraLogic Industrial Invoice Parser"],
  ];

  // Create a new workbook
  const workbook = XLSX.utils.book_new();

  // Create worksheet from data
  const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);

  // Set column widths
  worksheet["!cols"] = [{ wch: 20 }, { wch: 40 }];

  // Add the worksheet to workbook
  XLSX.utils.book_append_sheet(workbook, worksheet, "Invoice Data");

  // Generate Excel file and trigger download
  XLSX.writeFile(workbook, `${filename}_${Date.now()}.xlsx`);
}

// Export multiple invoices to Excel
export function exportMultipleToExcel(
  invoices: Array<ParsedInvoiceData & { id?: string; file_url?: string }>,
  filename: string = "invoices_export"
): void {
  // Create header row
  const headers = [
    "ID",
    "Vendor Name",
    "Invoice Date",
    "Total Amount",
    "Currency",
  ];

  // Create data rows
  const rows = invoices.map((invoice, index) => [
    invoice.id || `Invoice ${index + 1}`,
    invoice.vendor || "N/A",
    invoice.date || "N/A",
    invoice.amount || "N/A",
    invoice.currency || "N/A",
  ]);

  // Combine header and data
  const worksheetData = [
    ["VectraLogic - Bulk Invoice Export"],
    [],
    headers,
    ...rows,
    [],
    ["Total Records", invoices.length.toString()],
    ["Export Date", new Date().toISOString().split("T")[0]],
    ["Generated by", "VectraLogic Industrial Invoice Parser"],
  ];

  // Create workbook and worksheet
  const workbook = XLSX.utils.book_new();
  const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);

  // Set column widths
  worksheet["!cols"] = [
    { wch: 15 },
    { wch: 30 },
    { wch: 15 },
    { wch: 15 },
    { wch: 10 },
  ];

  // Add worksheet to workbook
  XLSX.utils.book_append_sheet(workbook, worksheet, "Invoices");

  // Generate and download
  XLSX.writeFile(workbook, `${filename}_${Date.now()}.xlsx`);
}

// Convert invoice data to CSV string (alternative export)
export function toCSV(data: ParsedInvoiceData): string {
  const headers = ["Vendor Name", "Invoice Date", "Total Amount", "Currency"];
  const values = [
    data.vendor || "",
    data.date || "",
    data.amount || "",
    data.currency || "",
  ];

  return `${headers.join(",")}\n${values.map((v) => `"${v}"`).join(",")}`;
}
